export const IS_SIGNUP_LOADING = "IS_SIGNUP_LOADING";
export const SIGNUP_SUBMITTED = "SIGNUP_SUBMITTED";

export const IS_OTP_LOADING = "IS_OTP_LOADING";
export const OTP_VERIFIED = "OTP_VERIFIED";

export const IS_RESEND_OTP_LOADING = "IS_RESEND_OTP_LOADING";
export const OTP_RESENT = "OTP_RESENT";

export const IS_LOGIN_LOADING = "IS_LOGIN_LOADING";
export const LOGIN_SUBMITTED = "LOGIN_SUBMITTED";
export const LOGOUT = "LOGOUT";

export const IS_FORGOT_PASSWORD_LOADING = "IS_FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUBMITTED = "FORGOT_PASSWORD_SUBMITTED";

export const IS_FORGOT_OTP_LOADING = "IS_FORGOT_OTP_LOADING";
export const FORGOT_OTP_VERIFIED = "FORGOT_OTP_VERIFIED";
export const RESET_TOKEN = "RESET_TOKEN";

export const IS_SET_PASSWORD_LOADING = "IS_SET_PASSWORD_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const SET_USER = "SET_USER";
export const SET_PENDING_EMAIL = "SET_PENDING_EMAIL";
